### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by andresbravog** [rposborne/wkhtmltopdf-heroku#11]
I'm trying to use this gem in my local osx dev environment and i'm getting an "cannot execute binary file" error.

So when i try to perform the command in console:

```bash
"/Users/myuser/.rvm/gems/ruby-1.9.3-p327@my-proyect/gems/wkhtmltopdf-heroku-1.0.0/bin/wkhtmltopdf-linux-amd64" -q  --footer-center "Center" --footer-left "Left" --footer-right "Right"       "file:////var/folders/8d/834zplp91pv8nr4bsxbgyhzr0000gn/T/wicked_pdf20130603-35780-1a0uwm9.html" "/var/folders/8d/834zplp91pv8nr4bsxbgyhzr0000gn/T/wicked_pdf_generated_file20130603-35780-1dupf6t.pdf"
```

i'm geting the error:
```bash
zsh: exec format error:
```

I can assume that is a dependency, any ideas??

**Comment by pallymore** [comment]
Hello @andresbravog  the binary included in this gem only works in Ubuntu 14.04 64-bit.
For development & testing, please use: https://github.com/pallymore/wkhtmltopdf-binary-edge
