### ISSUE TITLE
Find a New Maintainer. 

### ISSUE THREAD

**Issue by rposborne** [rposborne/wkhtmltopdf-heroku#14]
There is a lot of fragmentation in the forks.  Nothing too crazy has been added but it would be nice to bump the original gem. I would be more than happy to pick up some of the slack.

**Comment by dankozlowski** [comment]
@bradphelan Comments?  It would be nice to see this gem updated.

**Comment by threadhead** [comment]
Ok, @rposborne agreed to take over maintenance... 9 months ago. Where are we on assigning the repo to him? @bradphelan please.

**Comment by rposborne** [comment]
Hi Friends!

**Comment by pallymore** [comment]
I have forked the repo and pushed it as a new gem. It's using 0.12.2.1 binary built for Ubuntu 14. 

https://github.com/pallymore/wkhtmltopdf-heroku-edge

**Comment by nicolasmlv** [comment]
I confirm that i had to choose from one of the forks

But thank you @bradphelan for the gem and @pallymore for the fix, :+1:

**Comment by bradphelan** [comment]
Who want to take over the repo?

**Comment by rposborne** [comment]
@pallymore ?

**Comment by dankozlowski** [comment]
If @pallymore isn't interested any more, I'm happy to take over: I have a few apps in production that rely on this gem.

**Comment by bradphelan** [comment]
@rposborne has taken over the repository. Hope it is usefull to you guys. :)

**Comment by pallymore** [comment]
I can definitely do it.
I'm planning to maintain the `wkhtmltopdf-heroku-edge` gem anyways, I have a few production apps that use this too :)

**Comment by rposborne** [comment]
@dankozlowski, @pallymore  going to add you both as write access.   Between the three of us I am sure we can bring this back up to speed.

**Comment by dankozlowski** [comment]
Wicked.

**Comment by rposborne** [comment]
@bradphelan before you sign off completely can you pass rights for rubygems as well?
```
gem owner wkhtmltopdf-heroku -a russell {at} burningpony.com
```

**Comment by bradphelan** [comment]
Enter your RubyGems.org credentials.
Don't have an account yet? Create one at http://rubygems.org/sign_up
   Email:   bradphelan@xtargets.com
Password:
Pushing gem to https://rubygems.org...
Signed in.
Pushing gem to https://rubygems.org...
Owner added successfully.
Pushing gem to https://rubygems.org...
Owners for gem: wkhtmltopdf-heroku
- russell@burningpony.com
- bradphelan@xtargets.com
