### ISSUE TITLE
WickedPFP config

### ISSUE THREAD

**Issue by Celumproject** [rposborne/wkhtmltopdf-heroku#21]
How should we configure WickedPDF to make this work on heroku? Did not find any documentation on this config.

**Comment by pallymore** [comment]
Hello, 

You don't need to configure it manually if you are using this gem.
It's already included :) 
```
WickedPdf.config[:exe_path] = WKHTMLTOPDF_PATH
```

-P

**Comment by Celumproject** [comment]
Works seamlessly and perfectly. Thanks for the excellent work.
