### ISSUE TITLE
wkhtmltopdf 0.13

### ISSUE THREAD

**Issue by alonfixler** [rposborne/wkhtmltopdf-heroku#22]
Hey,
I really appreciate what you did with the complied version you created for heroku and it works great.
Do you think it will be possible to create one for the new 0.13 alpha version? It would help me a lot as I really want use the new webkit filters, which according to my tests are only supported in the new version.

Thanks,
Alon

**Comment by pallymore** [comment]
I will make a 0.13 branch :)

**Comment by alonfixler** [comment]
Thanks alot!

**Comment by pallymore** [comment]
Hello, could you try this in your gem file?

```
gem 'wkhtmltopdf-heroku', github: 'rposborne/wkhtmltopdf-heroku', branch: '2-12-3-0alpha'
```

**Comment by alonfixler** [comment]
Yeah I'll try it and let you know. I saw that you wrote in commit messgae:
"upgrade wkhtmltopdf version to 0.12.3.0". 
You meant 0.13, right?

**Comment by pallymore** [comment]
Yes...my bad. I need more coffee :) 
try this:
```ruby
gem 'wkhtmltopdf-heroku', github: 'rposborne/wkhtmltopdf-heroku', branch: ' 2-13-0-alpha'
```

**Comment by alonfixler** [comment]
I tried it and I got this error:
"Error: QXcbConnection: Could not connect to display"
I didn't get this error when I used your 0.12.2.1 file. I'm using node js on heroku.
By the way, was I suppose to upload anything else to heroku except for the wkhtmltopdf-linux-amd64 file?

**Comment by alonfixler** [comment]
I read a little bit about "Error: QXcbConnection: Could not connect to display" and the recommended solution was to add xvfb to my heroku buildpack. I did so and I stop getting this error and the pdf was generated. Unfortunately the webkit filters I desired were not applied although when I ran my app locally on a Windows env with the new 0.13 alpha version it worked perfectly. Do you have any ideas?

**Comment by pallymore** [comment]
hmm i'm not sure what may have caused that error - i'd prefer not to change the build-pack to make this work. I'll look into it later today.

About the filter issue - there is nothing i can do, could you report that in https://github.com/wkhtmltopdf/wkhtmltopdf ? 

Thanks,

**Comment by alonfixler** [comment]
I'm sorry,  it was my bad. It was created without filters because I still used the old wkhtmltopdf version. I still have to find a way to configure xvfb to my buildpack. Right now I can't seem to have a multi buildpack working.

**Comment by alonfixler** [comment]
By the way, Did you tried your complied file in heroku?

**Comment by pallymore** [comment]
no i haven't yet...will post update as soon as i get to it :(

**Comment by pallymore** [comment]
hey i just updated the branch with a custom build binary - could you try it? 

i was able to generate a pdf file without extra libs in my VM (similar to heroku cedar-14 stack) 

thanks.

**Comment by alonfixler** [comment]
Hey,
I just tried and I stopped getting those annoying errors I got before.Unfortunately those webkit-filters I want to apply that work in the Windows version doesn't seem to work. I guess I should address it to wkhtmltopdf people. Anyway, I really appreciate all your help.

**Comment by pallymore** [comment]
ok :) so that's most likely a wkhtmltopdf issue.

**Comment by alonfixler** [comment]
Hey,
I've installed Ubuntu on my computer and downloaded wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64 from the wkhtmltopdf website. When I tried to convert an html with css3 webkit filters everything worked fine. My conclusion is that the fact that your file didn't work for me on Heroku isn't a wkhtmltopdf issue but something else. I see now that it's supported both on windows and on linux with the new 0.13 alpha version.
Unfortunately, when I uploaded to Heroku the extracted content of the setup file I've downloaded I got the next error when I tried to use it: "Error: QXcbConnection: Could not connect to display".
Are you familiar with this kind of error? Can you please guide in building an Heroku wkhtmltopdf exec from the setup I've downloaded?
Thanks!

**Comment by pallymore** [comment]
Could you post a piece of your HTML/CSS file here? 
Have you tried the binary included in this branch? 

to build from source, you can find the instructions here:
https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md

**Comment by alonfixler** [comment]
My html is very simple. You just have to replace the name of the image.
What do you mean by "Have you tried the binary included in this branch"? I've used the your file:
wkhtmltopdf-linux-amd64 located at https://github.com/rposborne/wkhtmltopdf-heroku/tree/2-13-0-alpha/bin. Is there anything else I should use?

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <img src="DSCF0144.JPG" style="-webkit-filter:grayscale(1);"/>
</body>
</html>

**Comment by lynndylanhurley** [comment]
@pallymore - I installed from this branch, but it looks like the version is still `0.12.3`.

<img width="883" alt="screen shot 2016-06-06 at 2 08 27 pm" src="https://cloud.githubusercontent.com/assets/468037/15834284/4aabd968-2bf0-11e6-8acb-e8dbb92f71eb.png">

It's also rendering my content as if it's still version `0.12.3`. Can you verify that this branch is using the correct version?

**Comment by pallymore** [comment]
hello @lynndylanhurley 

yea you are right, for some reason it's still 0.12.3 :/ my bad.
I just updated it to 0.13.0-alpha, could you clear your bundler cache and try again?
(at 2-13-0-alpha@9bbb8ad)

Thanks,
P

![image](https://cloud.githubusercontent.com/assets/2566530/15835874/0e26392e-2c00-11e6-81c2-626511ffcfb4.png)

**Comment by lynndylanhurley** [comment]
Thanks for the quick response @pallymore!

I'm getting a fatal error:

~~~
Command Error: QXcbConnection: Could not connect to display
~~~

<img width="1305" alt="screen shot 2016-06-06 at 3 10 41 pm" src="https://cloud.githubusercontent.com/assets/468037/15836208/49c5a5fc-2bf9-11e6-85a1-0290e430843a.png">

It's also complaining about "unpatched QT" for some of the options. Any ideas?

**Comment by pallymore** [comment]
Unfortunately wkhtmltopdf 0.13 alpha is not headless, it needs a running x11 server to render the pages.
you will need to run it under `xvfb` 

eg. 
```bash
$ xvfb-run ./wkhtmltopdf test.html test.pdf
```

it's probably not gonna work with this gem right now, and it's definitely not recommended to be used in production.

**Comment by kayakyakr** [comment]
I just went through this process a year later, wanted to make a note for anyone trying it:

Used `heroku-buildpack-apt` w/ xvfb and the alpha deb from wkthmltopdf.org and then this guy's buildpack: https://github.com/captain401/heroku-buildpack-xvfb which is necessary to rewrite xvfb into something that can use the right paths.

It worked, yay!
