### ISSUE TITLE
Question about configuration

### ISSUE THREAD

**Issue by dmuneras** [rposborne/wkhtmltopdf-heroku#25]
Hi @rposborne,

I am using the gem ```wkhtmltopdf-binary``` to generate the pdfs in ```development```, should I use both gem? one to generate the pdfs in development and this one to be able to add ```wkhtmltopdf``` binary in heroku?

I am a bit confuse about the configuration of the gem. Should I change something in the wicked_pdf initializer to make this works on heroku?

Daniel.

**Comment by pallymore** [comment]
Hello @dmuneras,

For your first question - usually the answer is yes, but it depends. You don't have to use `wkhtmltopdf-binary` if you and all your team members are running your development environments under the same configuration as the production environment. (same Ubuntu 14.04 build)

Usually you don't have to change anything in your wicked_pdf initializer - just make sure you are not setting a binary path there. 

Thanks

**Comment by dmuneras** [comment]
@pallymore thanks a lot for your super quick answer.

Best regards,
Daniel.
