### ISSUE TITLE
Version date confusion

### ISSUE THREAD

**Issue by fschwahn** [rposborne/wkhtmltopdf-heroku#33]
It's quite confusing that the date of the latest version on rubygems is wrong (see here: https://rubygems.org/gems/wkhtmltopdf-heroku). It seems you forgot to update the date in the gemspec - I think you can just put in a dynamic date, so this will not happen anymore (something like `s.date = Time.now.strftime('%Y-%m-%d')`) and you don't have to manually update it.

**Comment by pallymore** [comment]
Ah, good point. I didn't even realize it was hardcoded. 
Fixed - it will be reflected in the next update (when wkhtmltopdf releases a new version) 
https://github.com/rposborne/wkhtmltopdf-heroku/commit/33a6a46623e970cb8fb6c9f8a7ff793358e0704b

Thanks!
