### ISSUE TITLE
Release 2.12.4.0 

### ISSUE THREAD

**Issue by pallymore** [rposborne/wkhtmltopdf-heroku#36]
Hello @rposborne, I have updated the version information and tested the gem locally. I think we are good to push this version to Rubygems.org 

This version of wkhtmltopdf introduces some bugs for my use cases - but I think other people may find it more useful than 0.12.3.0 

Thanks,
P

**Comment by rposborne** [comment]
@pallymore you now have release rights on rubygems 🎆

**Comment by rposborne** [comment]
2.12.4.0 has been shipped. Thanks @pallymore

**Comment by maxence33** [comment]
Hi. Is the gem good and still recommanded for Heroku-16 stack replacing Cedar-14 ?
thanks

**Comment by pallymore** [comment]
Hello, 

I don't think this can be used on Cedar-16 since it is built for ubuntu 14.04 LTS specifically. 

I will do some testing later this week and see if there is anything i can do. 

Thanks,
P

**Comment by maxence33** [comment]
Hi @pallymore that's great. I have just updated from Cedar 14 to 16 and just implemented Wickedpdf. Wasn't sure it would all work together but it's great it does. thank you. 
I will test proof it by the end of the week. I come back to you if i notice anything
