### ISSUE TITLE
Testing binary in development

### ISSUE THREAD

**Issue by abhishek77in** [rposborne/wkhtmltopdf-heroku#46]
`wkhtmltopdf` binary used on heroku outputs significantly different pdf on my development (mac) vs on production (heroku).

It would be really helpful to get some advice as how we can test the `wkhtmltopdf` functionality on local which is close to production.

My guess would be to run virtual box and setup ubuntu on it. But I would for some advise on this topic.

**Comment by abhishek77in** [comment]
To test in development I have setup a vagrant box with `ubuntu/trusty64` and it uses the `binary` that is used in production. This is quite close to my production and I am able to reproduce the issue with font size.

**Comment by pallymore** [comment]
Hi @abhishek77in sorry for the super late response.
The binary provided in this gem only works for heroku 18/16 which is based on Ubuntu (18/16 LTS). 
Heroku provides Docker images that you could use for testing / deployment. 

This gem merely provides the `wkhtmltopdf` executable to your app environment, if you have any issues with `wkthmltopdf` itself please check out https://github.com/wkhtmltopdf/wkhtmltopdf/issues
