### ISSUE TITLE
[feature request] auto-configure IMGKit gem

### ISSUE THREAD

**Issue by MathieuDerelle** [rposborne/wkhtmltopdf-heroku#49]
like you do for `pdfkit, wicked_pdf, and wisepdf`, maybe you could do it for https://github.com/csquared/IMGKit

```
IMGKit.configure do |config|
  config.wkhtmltoimage = WKHTMLTOPDF_PATH
end
```

**Comment by pallymore** [comment]
Hi @MathieuDerelle  - the `IMGKit` gem requires the `wkhtmltoimage` binary. 
Unfortunately right now we only provide `wkhtmltopdf` 

I don't mind if you fork this repo and make a separate gem for `wkhtmltoimage` 😄
