### ISSUE TITLE
webp images not supported

### ISSUE THREAD

**Issue by noctivityinc** [rposborne/wkhtmltopdf-heroku#51]
We just discovered that webp images are not supported in this version of wkhtmltopdf does not support webp images so they are displayed as broken images.

As of 2018, webp is supported in QT5.9... 0.12

Is there anyway to get webp support?

**Comment by pallymore** [comment]
Hi there - please open a ticket over here https://github.com/wkhtmltopdf/wkhtmltopdf instead.

this repo only provides the binary - there is not much else we can do about that here :(
