### ISSUE TITLE
Upgrading to 2.12.6.0 broke image display on Heroku

### ISSUE THREAD

**Issue by forrestblount** [rposborne/wkhtmltopdf-heroku#53]
We upgraded to 2.12.6.0 and this caused images to be dropped from our PDFs. We use WickedPDF and both the standard `image_tag` and `wicked_pdf_image_tag` started rendering as empty image squares in the generated PDFs.

Rolling back to 2.12.5.0 resolved the issue for us.

**Comment by pallymore** [comment]
Hi - this looks like a `wkhtmltopdf` issue - could you also open a ticket over there? https://github.com/wkhtmltopdf/wkhtmltopdf/issues 

Thanks!

**Comment by cseelus** [comment]
Works still great for our Rails 7.0 app with Wicked PDF 2.6.3, for all common image formats (included with the `image_tag` helper) and even HTML canvas based graphics. 

For the few SVG files we use, we had to inline them (using the [`inline_svg` gem for Rails](https://github.com/jamesmartin/inline_svg)).

<img width="923" alt="Screen Shot 2022-09-03 at 18 03 04" src="https://user-images.githubusercontent.com/3188392/188278958-77be8535-b744-4c8c-b233-a2b26c3f7792.png">

**Comment by b3nty** [comment]
Hi - in my case `Rails 6` and `wkhtmltopdf-heroku 2.12.6.1.pre.jammy`, I had to use `image_tag wicked_pdf_asset_base64("image.jpg")` for pictures in `assests/images`.

hope this can help !

**Comment by mattbrictson** [comment]
Confirmed that rolling back to 2.12.5.0 fixes broken images on Heroku-20.
