### ISSUE TITLE
Experimental support for Stack-22

### ISSUE THREAD

**Issue by spickermann** [rposborne/wkhtmltopdf-heroku#56]
Hey there,

I noticed that 2.12.6.1.pre.jammy was released sometime ago. I wonder how you feel about releasing a non-pre version of it? 

Did you get some feedback about this version? Are there any known issues? Or would you consider it production ready, and can you recommend using it?

**Comment by pallymore** [comment]
Hi 👋🏻 

Thanks - I haven't seen any feedback / comments regarding that version - however at the same time I haven't had a chance to test it thoroughly myself. 
At this moment I'm not sure how to release this as it's not backward compatible with Heroku 20 or 18 - it's probably going to be a major version bump. 

I think it's fine to use this in production as long as you have sufficiently tested your use cases - results from wkhtmltopdf are often heavily depend on how the pages are implemented.

**Comment by spickermann** [comment]
Hey, I just wanted to let you know that we have been using `2.12.6.1.pre.jammy` for the last 10 days in production on stack22 on Heroku. No issues at all. Works fine and as expected. Thank you!

**Comment by MicahBrown** [comment]
Also using `2.12.6.1.pre.jammy` in production for a few days and haven't noticed any issues yet.

**Comment by pallymore** [comment]
Hi all - thank you for the responses!

I've pushed a new major version for `jammy` support:

https://rubygems.org/gems/wkhtmltopdf-heroku/versions/3.0.0.pre.rc0 

Changelog: https://github.com/rposborne/wkhtmltopdf-heroku/blob/main-v3/CHANGELOG.md#300prerc0---2023-02-07 

It's exactly the same as `2.12.6.1.pre.jammy` - just a major version bump. I will make a prod release once I get a chance to test it myself. Thanks again

**Comment by jeffbax** [comment]
Do we expect that this will remain compatible with 18/20 or is this 22 only?

**Comment by pallymore** [comment]
I haven't tested them in 18/20 but my impression is it only works in heroku-22 due to the underlying dependency changes.

**Comment by jeffbax** [comment]
@pallymore thanks for the heads up, appreciate it!

**Comment by jeffbax** [comment]
Gave this a shot in a review app on Heroku-22 and seemed to be working fine and will be using it to upgrade our pipeline

**Comment by pallymore** [comment]
thanks!

**Comment by jslag** [comment]
from a quick test on our app, `2.12.6.1.pre.jammy` is not getting styling or images that were working previously.

**Comment by pallymore** [comment]
Hi - sorry I haven't been checking Github for a while. Sounds like everyone is happy with `3.0.0.pre.rc0` 😁 I can publish `3.0.0` later today

**Comment by pallymore** [comment]
Hi all - 3.0.0 is out. thanks!
