### ISSUE TITLE
`3.0.0.pre.rc0` and `heroku-stack-20` not working

### ISSUE THREAD

**Issue by alessandrostein** [rposborne/wkhtmltopdf-heroku#58]
Hi friends,

Just feedback around `heroku-stack-20` and `'wkhtmltopdf-heroku', '3.0.0.pre.rc0'`. They are not compatible.

``` ruby
# Herok
Heroku stack: 20
```

```ruby
# Gemfile
gem 'wkhtmltopdf-heroku', '3.0.0.pre.rc0' 
```

Raised this exception
```ruby
RuntimeError: Failed to execute: ["/app/vendor/bundle/ruby/3.2.0/gems/wkhtmltopdf-heroku-3.0.0.pre.rc0/bin/wkhtmltopdf-linux-amd64", "--page-size", "Letter", "--margin-top", "13", "--margin-bottom", "3...
```

**Comment by msencenb** [comment]
@alessandrostein did you find a way to fix this? Or did you just downgrade for heroku-20?

**Comment by alessandrostein** [comment]
> ```ruby
> wkhtmltopdf-heroku
> ```

Was not working with Heroku-20, so, upgrade to Heroku-22 and now it's working fine 👍
