### ISSUE TITLE
issue / question

### ISSUE THREAD

**Issue by nat** [rposborne/wkhtmltopdf-heroku#6]
hi, so I've posted a similar question with camdez/wkhtmltopdf-heroku, but it seems you both may be interested in this.. 

Now I'd love to use your gem, but when I include it in bundler with:

gem "wkhtmltopdf-heroku"
and I say bundle show wkhtmltopdf-heroku
When I go to the directory, it takes up just 11 MB - which is good. yay.

and when I do a bundle install, push to heroku and my heroku instance crashes with the following log: (boo!) :).

app[web.1]: /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.2/lib/bundler/runtime.rb:74:in require': no such file to load -- wkhtmltopdf/heroku (LoadError)
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.2/lib/bundler/runtime.rb:74:inrescue in block in require'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.2/lib/bundler/runtime.rb:62:in block in require'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.2/lib/bundler/runtime.rb:55:ineach'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.2/lib/bundler/runtime.rb:55:in require'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:119:inrequire'
app[web.1]: from /app/config/application.rbin <top (required)>'
app[web.1]: from /app/config/environment.rb:2:inrequire'
app[web.1]: from /app/config/environment.rbin <top (required)>'
app[web.1]: from /app/config.ru:3:inrequire'
app[web.1]: from /app/config.ruin block in <main>'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.2.3/lib/rack/builder.rb:46:ininstance_eval'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.2.3/lib/rack/builder.rb:46:in initialize'
app[web.1]: from /app/config
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/rack/adapter/loader.rb:36:ineval'
app[web.1]: from /app/config.ruin <main>'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/rack/adapter/loader.rb:36:inload'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/rack/adapter/loader.rb:45:in for'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/thin/controllers/controller.rb:169:inload_adapter'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/thin/controllers/controller.rb:73:in start'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/thin/runner.rb:185:inrun_command'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/lib/thin/runner.rb:151:in run!'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/gems/thin-1.2.11/bin/thin:6:in'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/bin/thin:19:in load'
app[web.1]: from /app/vendor/bundle/ruby/1.9.1/bin/thin:19:in'

So I've resorted to using this in my bundler:
gem "wkhtmltopdf-heroku", :git => 'git://github.com/camdez/wkhtmltopdf-heroku.git'

And while it works, (yay!!), it also takes up 34 MB of slug size because the .git repository seems to be included in my deployment :(.

I can tell because when I say:
bundle show wkhtmltopdf-heroku
and cd to the directory and do a du -h, I see the bad news.

Do you know how I can fix this and get a smaller slug size in heroku cedar?

Thanks!

**Comment by pallymore** [comment]
It seems this is related to @camdez fork. Could you try to use the original gem again once it's updated?
